#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d                            
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        0
bspc config window_gap          20

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
