include config.mk

SRC = drw.c dwm.c util.c
# --- Wallpaper Logic Trigger ---
ifneq (,$(filter wall,$(MAKECMDGOALS)))
    SRC += wall.c
    CPPFLAGS += -DWALL_ENABLE
    # Add Imlib2 only if it's not already there
    ifeq (,$(findstring -lImlib2,$(LIBS)))
        LIBS += -lImlib2
    endif
endif

OBJ = ${SRC:.c=.o}

all: dwm

.c.o:
	${CC} -c ${CFLAGS} ${CPPFLAGS} $<

${OBJ}: config.h config.mk

config.h:
	cp config.def.h $@

# Use LIBS specifically to ensure correct order
dwm: ${OBJ}
	${CC} -o $@ ${OBJ} ${LDFLAGS} ${LIBS}

clean:
	rm -f dwm ${OBJ} wall.o dwm-${VERSION}.tar.gz

install: all
	mkdir -p ${DESTDIR}${PREFIX}/bin
	cp -f dwm ${DESTDIR}${PREFIX}/bin
	chmod 755 ${DESTDIR}${PREFIX}/bin/dwm

uninstall:
	rm -f ${DESTDIR}${PREFIX}/bin/dwm

# This makes 'make wall' trigger 'make all'
wall: all
	@:

.PHONY: all clean dist install uninstall wall
